#启动端口
server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8

#应用名称
spring:
  application:
    name: authority-system
    #Thymeleaf取消缓存
  thymeleaf:
    cache: false
    #jpa的配置
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    #数据库配置

  datasource:
    dynamic:
      primary: base
      datasource:
        base:
          url: jdbc:mysql://localhost:3306/authoritysystem?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: root
        quartz:
          url: jdbc:mysql://localhost:3306/febs_quartz?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: root


  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
     # 超时时间
    timeout: 0

    jedis:
      pool:
        max-active: 2000

        min-idle: 8

        max-idle: 500

        max-wait: 10000
#  jedis:
#    pool:
#      # 连接池中的最小空闲连接
#      min-idle: 8
#      # 连接池中的最大空闲连接
#      max-idle: 500
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 2000
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: 10000
